### ISSUE TITLE
not unenrolling on corsola (steelix)

### ISSUE THREAD

**Issue by iamextremelydisappointed** [BinBashBanana/badrecovery#11]
![IMG_2789](https://github.com/user-attachments/assets/b3c54bd8-9998-4228-bbde-2f11e35719a5)
for some reason, badrecovery would not unenroll my chromebook. i tried it like 5-7 times from my own image and a prebuilt one and it still wouldn't work. could this be one of the chromebooks with the fwmp issue?
my chromebook is a Lenovo 300e Yoga Chromebook Gen 4 released around november 2023

**Comment by BinBashBanana** [comment]
a workaround will be released soon

**Comment by iamextremelydisappointed** [comment]
ok

**Comment by appleflyerv3** [comment]
> a workaround will be released soon

facts

**Comment by BinBashBanana** [comment]
@iamextremelydisappointed fixed in https://github.com/BinBashBanana/badrecovery/commit/57b0ea91dd408b2b1e7752fc5a7af669b7ce2de9
