### ISSUE TITLE
WARNING! ! ! Installation of software failed. Displaying hw diganostics

### ISSUE THREAD

**Issue by awesome769** [BinBashBanana/badrecovery#16]
I get this when i try to use badrecovery

Checking for an offcial recovery image . . . Looking ro rootfs using kern_guid. . .  .  .  .  .  .  .  .  .Found /dev/sda3
Extracting the device mapper configuration. . .Created device mapper root vroot
Mounting usb .ok
Re-binding /sys /proc /dev for /usb
Done.
Beggning system recovery from /dev/sda
Checking the install kernel for valid versions and signature . . .
Rollback version stored in the TPM 0x10003
Resettings secuirty device . . .error clobbering lockbox space: 132
 done.
Verifying RW_VPD
Found RW_VPD sysfs.
Installing software; this will take some time.
See the debug log on VT3 for the full output.
WARNING! ! ! Installation of software failed. Displaying hw diganostics
Missing hardware diagnostics.
Dumping dmesg to /log
Copying firmware log to /log
Saving log files from: /log -> /dev/sda1
Failures seen trying to save log file

**Comment by BinBashBanana** [comment]
What's your board and what version recovery image are you using?

**Comment by awesome769** [comment]
The board is octopus i have received a image from here

https://dl.darkn.bio/BadRecovery/postinst

**Comment by awesome769** [comment]
i will ask the person that built it (darkn) for the version he used and yes im not in developer mode im on kernver 3

**Comment by BinBashBanana** [comment]
It sounds like a bad flash or a bad USB drive. Try redownloading and using a different USB drive.
