### ISSUE TITLE
RELEASE DATE

### ISSUE THREAD

**Issue by 7Frost7** [BinBashBanana/badrecovery#3]
Olybmmer has a wrong release date

**Comment by kkilobyte** [comment]
duplicate of #2

**Comment by liujustin604** [comment]
> duplicate of #2

how is an issue a duplicate of a PR?

**Comment by kkilobyte** [comment]
> how is an issue a duplicate of a PR?
the PR fixes the issue

**Comment by liujustin604** [comment]
> > how is an issue a duplicate of a PR?
> 
> 
> 
> the PR fixes the issue

then it should be marked as such, and not as a duplicate

**Comment by SilverGamer5934** [comment]
Oily boomer please release
