### ISSUE TITLE
error when compiling basic (corsola)

### ISSUE THREAD

**Issue by threefourh** [BinBashBanana/badrecovery#7]
when I compile basic for my steelix (corsola) chromebook, I get an error

Info: Creating loop device
Info: Detected version: 119
Info: Detected architecture: arm
Info: Detected chunks: 4
Info: Detected LVM stateful: yes
Info: Detected ROOT-A size: 4.0GiB
Info: Detected layout v3: yes
Info: Detected kernel version: 5.15
Info: Detected big date support: yes
Info: Supports postinst: no
Info: Supports postinst_sym: yes
Info: Supports persist: no
Info: Supports basic: yes
Info: Supports unverified: yes
Info: Using type: basic
Info: Creating stateful payload
Info: Setting up encstateful
Info: Creating encstateful
Info: Payload size: 64MiB
Info: Maximum new image size: 5.1GiB
Info: Moving partitions: 4
Info: Resizing ROOT-A
ERROR: Starting LBA overlaps
ERROR: -i 3 -s 8527872 
"$CGPT" add "$LOOPDEV" -i 3 -s "$((ROOTA_NEW_SIZE / SECTOR_SIZE))" failed with exit code 1. THIS IS A BUG, PLEASE REPORT!

my chromebook is keyrolled

**Comment by threefourh** [comment]
same thing happens when compiling on web

**Comment by BinBashBanana** [comment]
fixed
