### ISSUE TITLE
errors when on badrecovery screen

### ISSUE THREAD

**Issue by idkidk738374** [BinBashBanana/badrecovery#9]
![16D979DD-4966-4A43-B821-EFB71F9DAB67](https://github.com/user-attachments/assets/7ac24c2a-63db-469a-8e84-b462485b53ad)

after this i did reboot -f and it booted to normal mode, did i do something wrong?

**Comment by alandoesthings** [comment]
I did wait over 5 minutes when this came up btw

**Comment by BinBashBanana** [comment]
you need to do this in verified mode like the instructions say.
